server:
  port: 8082
#spring: 
#  cloud:
#    config: 
#      discovery: 
#        serviceId: config
#        enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
  server: 
    waitTimeInMsWhenSyncEmpty: 0