server: 
  port: 8091
  servlet:
    context-path: /client
app:  
  client: 
    clientId: app2
    clientSecret: app2secret
    accessTokenUri: http://localhost:8083/oauth/token
    checkTokenUri: http://localhost:8083/oauth/check_token
    tokenName: token
logging:
  level:
    root: INFO
    