server:
  port: 8081
logging: 
  level: 
    root: info  
spring:
  application: 
    name: config
  profiles: 
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
 #       git: 
 #         uri: file:/Users/phamhoanglinh/git/cloud # local git 
 #         search-paths: '*'


