server:
  port: 8084
app: 
  resource: 
    id: my_resource_id
spring:
  h2: 
    console: 
      enabled: true
      path: /h2  
  datasource: 
    url: jdbc:h2:file:~/accountdb
    username: sa
    password: 
  jpa:
    show-sql: false
    hibernate: 
      ddl-auto: create-drop
    properties:
      hibernate: 
        dialect: org.hibernate.dialect.H2Dialect