eureka: 
  instance: 
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER}/eureka/
## ---------------------
## -- app properties ---
## ---------------------
app: 
  internal: 
    user: SERVER
    password: SERVER_PWD
    role: SERVER