package com.spring.aws;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class AwsApplicationTest {
    @Test public void testSomeLibraryMethod() {
        AwsApplication classUnderTest = new AwsApplication();
       
    }
}
